import os
import json
import random
import logging
import requests
import re
import time
try:
    import anthropic
except ImportError:
    anthropic = None
from typing import List
from alpha_candidate import AlphaCandidate
from validator import normalize_expression_aliases

logger = logging.getLogger(__name__)

# Try importing dotenv for external configs
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

class RAGMutator:
    """
    RAG-powered Mutator Engine tailored for Elite F1 Alpha Pipeline.
    Loads highly successful alphas (DNA) and injects them into LLM prompt
    context to constrain and guide generation.
    """
    
    def __init__(self, seed_file: str = "data/elite_alphas/elite_seed.json", model_name="stepfun/step-3.5-flash:free"):
        self.openai_base = os.getenv("OPENAI_API_BASE", "https://openrouter.ai/api/v1")
        self.api_url = f"{self.openai_base.rstrip('/')}/chat/completions"
        self.model_name = os.getenv("LLM_MODEL", model_name)
        self.api_key = os.getenv("OPENAI_API_KEY") or os.getenv("OPENROUTER_API_KEY", "")
        self.anthropic_key = os.getenv("ANTHROPIC_API_KEY", "")
        self.anthropic_base_url = os.getenv("ANTHROPIC_BASE_URL", "https://api.anthropic.com")
        
        self.anthropic_client = None
        if anthropic and self.anthropic_key:
            try:
                self.anthropic_client = anthropic.Anthropic(
                    api_key=self.anthropic_key,
                    base_url=self.anthropic_base_url
                )
                logger.info(f"🦾 Anthropic client initialized with base_url: {self.anthropic_base_url}")
            except Exception as e:
                logger.error(f"❌ Failed to initialize Anthropic client: {e}")

        self.last_attempted = 0
        self.last_succeeded = 0
        self.last_error_rate = 0.0
        if not self.api_key and not self.anthropic_key:
            logger.warning("⚠️ No LLM API keys (OPENROUTER/ANTHROPIC/OPENAI) missing. RAG generation is disabled.")
        else:
            provider = "OpenAI-Compatible" if "openrouter.ai" not in self.openai_base else "OpenRouter"
            logger.info(f"🤖 RAG Mutator using {provider} ({self.openai_base}) with model {self.model_name}")
        
        # Load Elite Seeds
        self.elite_seeds = []
        seed_path = os.path.join(os.path.dirname(__file__), seed_file)
        if os.path.exists(seed_path):
            try:
                with open(seed_path, 'r') as f:
                    self.elite_seeds = json.load(f)
                logger.info(f"🧬 Loaded {len(self.elite_seeds)} Elite DNA seeds from {seed_path}")
            except Exception as e:
                logger.error(f"❌ Failed to load Elite Seeds: {e}")
        else:
            logger.warning(f"⚠️ Seed file not found at {seed_path}. Will run without RAG context.")
            
    def _pick_context_dna(self, n=3):
        """Randomly pick top performing DNA strings."""
        if not self.elite_seeds:
            return []
        
        # Filter top seeds
        high_performers = [s['expression'] for s in self.elite_seeds if s.get('sharpe', 0) >= 1.25]
        if not high_performers:
            high_performers = [s['expression'] for s in self.elite_seeds]
            
        return random.sample(high_performers, min(n, len(high_performers)))

    def _fetch_negative_examples(self, n=3) -> List[str]:
        """Fetch recently failed alphas generated by RAG."""
        db_path = os.path.join(os.path.dirname(__file__), "alpha_results.db")
        recent_fails = []
        if os.path.exists(db_path):
            try:
                import sqlite3
                with sqlite3.connect(db_path) as conn:
                    cursor = conn.cursor()
                    # Get recent RAG alphas that either failed structural checks or got poor Sharpe
                    cursor.execute('''
                        SELECT expression FROM alphas 
                        WHERE theme='rag_llm' AND error='' AND sharpe < 0.5 
                        ORDER BY id DESC LIMIT ?
                    ''', (n,))
                    recent_fails = [r[0] for r in cursor.fetchall()]
            except Exception as e:
                logger.warning(f"Could not load recent fails: {e}")
        return recent_fails

    def _fetch_dna_hints(self) -> str:
        """Fetch statistical operator hints from AlphaDNA generator_weights.json."""
        weights_path = os.path.join(os.path.dirname(__file__), "generator_weights.json")
        if os.path.exists(weights_path):
            try:
                with open(weights_path, 'r') as f:
                    w_data = json.load(f)
                    ops = w_data.get("operator_weights", {})
                    if ops:
                        sorted_ops = sorted(ops.items(), key=lambda x: x[1])
                        worst = [op for op, v in sorted_ops[:3]]
                        best = [op for op, v in sorted_ops[-4:]]
                        return f"STATISTICAL HINT: Avoid operators with recent low winrates like {worst}. Strongly prefer top-performing operators like {best}."
            except Exception as e:
                logger.warning(f"Could not load DNA weights: {e}")
        return ""

    def _build_prompt(self, dna_context: List[str], recent_fails: List[str] = None, dna_hints: str = "") -> str:
        prompt = "You are a Quantitative Researcher expert in WorldQuant Brain.\n"
        prompt += "Your task is to generate novel, mathematically sound alpha formulas using the WorldQuant Alpha platform syntax.\n\n"
        
        if dna_context:
            prompt += "✅ POSITIVE EXAMPLES (Learn from these):\n"
            prompt += "Here are some highly successful 'Elite' alpha expressions that passed simulation with high Sharpe:\n"
            for i, dna in enumerate(dna_context, 1):
                prompt += f"Elite Alpha {i}: {dna}\n"

        if recent_fails:
            prompt += "\n🔴 NEGATIVE ANTI-PATTERNS (AVOID THESE):\n"
            prompt += "The following alphas were recently generated but FAILED simulation (e.g. negative Sharpe).\n"
            prompt += "Analyze their structures and DO NOT generate formulas suspiciously similar to these:\n"
            for i, fail in enumerate(recent_fails, 1):
                prompt += f"Failed Alpha {i}: {fail}\n"
                
        if dna_hints:
            prompt += f"\n💡 {dna_hints}\n"

        if dna_context:
            prompt += "\nINSTRUCTIONS:\n"
            prompt += "1. Study the structure, operator groupings, and logic of the Elite alphas above.\n"
            prompt += "2. CRITICAL: Pay attention to the SIGN of the expressions. Many successful alphas are REVERSAL signals (starting with -1 * or -rank).\n"
            prompt += "3. STABILITY: Avoid using raw 1-day 'returns' as the core signal. Use longer lookbacks (e.g., ts_delta(x, 5), ts_mean(x, 20), ts_corr(x, y, 10)) to keep Turnover < 70%.\n"
            prompt += "4. NOVELTY: Do NOT strictly copy. Create a completely newly mixed alpha (F1 Generation).\n"
            prompt += "5. STRUCTURE: AVOID using 'rank()' as the primary outer wrapper. Use advanced operators like 'group_neutralize(', 'zscore(', 'ts_zscore(', 'group_zscore(', or 'scale('.\n"
            prompt += "   Example of robust reversal: 'group_neutralize(-1 * ts_rank(ts_delta(close, 5), 20), subindustry)'\n"
        else:
            prompt += "INSTRUCTIONS: Generate a robust mean-reversion (reversal) alpha. Use signs like -1 * ... and lookbacks > 5 days. DO NOT rely on basic 'rank(...)'. Explore 'group_neutralize' or 'zscore'.\n"
            
        prompt += "\nFormat your response by ONLY providing the final mathematical expression. NO markdown, NO text, NO explanation. Just the raw string."
        return prompt

    def _clean_response(self, text: str) -> str:
        """Strip markdown and text around the formula."""
        lines = text.strip().split('\n')
        for line in reversed(lines):
            line = line.strip().strip('`').strip().strip('"').strip("'")
            if any(op in line for op in ['rank', 'volume', 'close', 'open', 'delay', 'returns', 'ts_']):
                return line
        return lines[-1].strip('`').strip()

    def generate_f1_alphas(self, batch_size=3) -> List[AlphaCandidate]:
        """
        Generate multiple F1 Elite Candidates using RAG LLM asynchronously.
        """
        import concurrent.futures
        
        candidates = []
        if not self.api_key:
            self.last_attempted = batch_size
            self.last_succeeded = 0
            self.last_error_rate = 1.0
            return candidates
        logger.info(f"🧠 Prompting OpenRouter for {batch_size} Elite AI Alphas in parallel...")
        
        # Optimize with Connection Pooling for parallel requests
        session = requests.Session()
        adapter = requests.adapters.HTTPAdapter(pool_connections=32, pool_maxsize=32)
        session.mount('https://', adapter)
        session.mount('http://', adapter)
        session.headers.update({
            "HTTP-Referer": "https://worldquant-alpha-factory.local", 
            "Content-Type": "application/json"
        })
        if self.api_key:
            session.headers["Authorization"] = f"Bearer {self.api_key}"
        
        # Cache global hints so we don't query DB for each thread concurrently
        global_recent_fails = self._fetch_negative_examples(n=3)
        global_dna_hints = self._fetch_dna_hints()

        def _fetch_one():
            dna_context = self._pick_context_dna(n=3)
            prompt = self._build_prompt(dna_context, global_recent_fails, global_dna_hints)
            max_retries = 10
            retry_delay = 10

            # Option A: Anthropic
            is_anthropic_model = self.model_name.startswith("claude")
            if self.anthropic_client and (is_anthropic_model or not self.api_key):
                for attempt in range(max_retries):
                    try:
                        logger.info(f"🔮 Prompting Anthropic ({self.model_name}) [Attempt {attempt+1}/{max_retries}]...")
                        message = self.anthropic_client.messages.create(
                            model=self.model_name,
                            max_tokens=1024,
                            messages=[
                                {"role": "user", "content": prompt}
                            ]
                        )
                        raw_text = message.content[0].text if message.content else ""
                        clean_expr = normalize_expression_aliases(self._clean_response(raw_text))
                        if clean_expr and len(clean_expr) > 10:
                            logger.info(f"💡 AI (Anthropic) Generated formula: {clean_expr}")
                            return AlphaCandidate(
                                expression=clean_expr,
                                theme="rag_llm",
                                family="elite_f1",
                                mutation_type="llm_rag_injection"
                            )
                    except Exception as e:
                        logger.error(f"Anthropic API Error (Attempt {attempt+1}): {e}")
                        if attempt < max_retries - 1:
                            time.sleep(retry_delay)
                            continue
                if not self.api_key: return None # Fallback only if we have OpenRouter
            
            # Option B: OpenRouter
            if not self.api_key:
                return None

            model_candidates = [self.model_name, "openrouter/auto"]
            for model_name in model_candidates:
                if model_name.startswith("claude") and not is_anthropic_model:
                    pass

                for attempt in range(max_retries):
                    payload = {
                        "model": model_name,
                        "messages": [
                            {"role": "user", "content": prompt}
                        ],
                        "temperature": 0.8,
                        "top_p": 0.95
                    }
                    try:
                        response = session.post(self.api_url, json=payload, timeout=60)
                        if response.status_code == 200:
                            raw_text = response.json().get('choices', [{}])[0].get('message', {}).get('content', '')
                            clean_expr = normalize_expression_aliases(self._clean_response(raw_text))
                            if clean_expr and len(clean_expr) > 10:
                                logger.info(f"💡 AI (OpenRouter) Generated formula: {clean_expr}")
                                return AlphaCandidate(
                                    expression=clean_expr,
                                    theme="rag_llm",
                                    family="elite_f1",
                                    mutation_type="llm_rag_injection"
                                )
                        elif response.status_code in (502, 503, 504, 429):
                            logger.warning(f"OpenRouter API {response.status_code} (Attempt {attempt+1}/{max_retries}), retrying in {retry_delay}s...")
                            if attempt < max_retries - 1:
                                time.sleep(retry_delay)
                                continue
                        elif response.status_code in (400, 404) and model_name != "openrouter/auto":
                            logger.warning(
                                f"Model '{model_name}' unavailable ({response.status_code}), "
                                "retrying with openrouter/auto"
                            )
                            break # Try next model
                        else:
                            logger.error(f"OpenRouter API Error: {response.status_code} - {response.text}")
                            break # Non-retryable
                    except requests.exceptions.RequestException as e:
                        logger.error(f"Failed to connect to LLM (Attempt {attempt+1}): {e}")
                        if attempt < max_retries - 1:
                            time.sleep(retry_delay)
                            continue
                    except Exception as ex:
                        logger.error(f"Unexpected error in _fetch_one (Attempt {attempt+1}): {ex}")
                        break
            return None

        # Execute all HTTP requests concurrently
        attempted = batch_size
        with concurrent.futures.ThreadPoolExecutor(max_workers=min(8, batch_size)) as executor:
            for result in executor.map(lambda _: _fetch_one(), range(batch_size)):
                if result:
                    candidates.append(result)
        self.last_attempted = attempted
        self.last_succeeded = len(candidates)
        self.last_error_rate = 1.0 - (len(candidates) / attempted if attempted else 0.0)
        return candidates

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    rag = RAGMutator()
    cands = rag.generate_f1_alphas(batch_size=2)
    for c in cands:
        print(c.expression, c.family, c.theme)
